// Generated by CoffeeScript 1.3.3
(function() {
  var all_data, display, init, init_manual, manual_data, root, set_music, set_people_table, set_total, web_data;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  web_data = [];

  manual_data = [];

  all_data = [];

  set_total = function(people, div_id) {
    var total;
    total = 0;
    _.each(people, function(d) {
      return total += d.total;
    });
    return $(div_id).html(total);
  };

  set_people_table = function(people, table_id) {
    var html;
    html = "<thead><tr><th>Name</th><th>Count</th></tr></thead>\n<tbody>";
    _.each(people, function(d) {
      return html += "<tr><td>" + d.name + "</td><td>" + d.total + "</td></tr>";
    });
    html += "</tbody>";
    return $(table_id).html(html);
  };

  set_music = function(people, table_id) {
    var html, music_lovers;
    music_lovers = _.filter(people, function(d) {
      return d.music.length > 0;
    });
    html = "<thead><tr><th>Name</th><th>Song</th></tr></thead>\n<tbody>";
    _.each(music_lovers, function(d) {
      return html += "<tr><td>" + d.name + "</td><td>" + d.music + "</td></tr>";
    });
    html += "</tbody>";
    return $(table_id).html(html);
  };

  display = function(mdata, tabletop) {
    var data, people_coming, people_declining;
    manual_data = mdata;
    _.each(manual_data, function(d) {
      d.name = d['name'];
      d.total = parseInt(d['total']);
      d.attending = d['attending'] === 'yes';
      return d.music = d['music'];
    });
    _.each(web_data, function(d) {
      d.name = d['namesofattendees'];
      d.total = parseInt(d['totalnumberattending']);
      d.attending = d['willyoubeattending'] === "Can't wait!";
      return d.music = d['weretakingrequests'];
    });
    data = web_data.concat(manual_data);
    all_data = data;
    people_coming = _.filter(data, function(d) {
      return d.attending === true;
    });
    people_declining = _.filter(data, function(d) {
      return d.attending === false;
    });
    set_total(people_coming, '#total_count');
    set_people_table(people_coming, '#who_table');
    set_music(data, '#music_table');
    set_total(people_declining, '#decline_count');
    return set_people_table(people_declining, '#decline_table');
  };

  init_manual = function(data, tabletop) {
    web_data = data;
    return Tabletop.init({
      key: '0Aphqt-W5Px29dDN3NUdKSS1mS0pEQ2JDSkVqN0tlZ3c',
      callback: display,
      simpleSheet: true
    });
  };

  init = function() {
    return Tabletop.init({
      key: '0Aphqt-W5Px29dDdxZkxJaDd0dGRGaE02YmNvTDJPYVE',
      callback: init_manual,
      simpleSheet: true
    });
  };

  $(function() {
    return init();
  });

}).call(this);
